# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/mult19/mult19.xci
# IP: The module: 'mult19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/mult19/mult19_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult19'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/mult19/mult19.xci
# IP: The module: 'mult19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/mult19/mult19_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult19'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
