
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2
SW Build 913775 on Wed May 14 18:34:48 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdmaps.h"

/*
* The configuration table for devices
*/

XDmaPs_Config XDmaPs_ConfigTable[] =
{
	{
		XPAR_PS7_DMA_NS_DEVICE_ID,
		XPAR_PS7_DMA_NS_BASEADDR
	},
	{
		XPAR_PS7_DMA_S_DEVICE_ID,
		XPAR_PS7_DMA_S_BASEADDR
	}
};


