# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/add64/add64.xci
# IP: The module: 'add64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/add64/add64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/add64/add64.xci
# IP: The module: 'add64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/immesys/w/FPGA/edxcel/partproject/partproject.srcs/sources_1/ip/add64/add64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'add64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
