
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 2014.2
* DO NOT EDIT.
*
* hsm v2014.2
SW Build 913775 on Wed May 14 18:34:48 MDT 2014
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdevcfg.h"

/*
* The configuration table for devices
*/

XDcfg_Config XDcfg_ConfigTable[] =
{
	{
		XPAR_PS7_DEV_CFG_0_DEVICE_ID,
		XPAR_PS7_DEV_CFG_0_BASEADDR
	}
};


