# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/immesys/w/FPGA/project/hardware/ip_repo/EdXel_1.1/EdXel_v1_1_project/EdXel_v1_1_project.cache/wt [current_project]
set_property parent.project_path /home/immesys/w/FPGA/project/hardware/ip_repo/EdXel_1.1/EdXel_v1_1_project/EdXel_v1_1_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/immesys/w/FPGA/project/hardware/ip_repo/EdXel_1.1 [current_project]
read_verilog -library xil_defaultlib {
  /home/immesys/w/FPGA/project/hardware/ip_repo/EdXel_1.1/EdXel_v1_1_project/EdXel_v1_1_project.srcs/sources_1/new/DummyEPU.v
  /home/immesys/w/FPGA/project/hardware/ip_repo/EdXel_1.1/hdl/EdXel_v1_1_S00_AXI.v
  /home/immesys/w/FPGA/project/hardware/ip_repo/EdXel_1.1/hdl/EdXel_v1_1.v
}
catch { write_hwdef -file EdXel_v1_1.hwdef }
synth_design -top EdXel_v1_1 -part xc7z010clg400-1
write_checkpoint EdXel_v1_1.dcp
catch { report_utilization -file EdXel_v1_1_utilization_synth.rpt -pb EdXel_v1_1_utilization_synth.pb }
